//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by 3dViewer.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_POINTER                     104
#define IDR_MAINFRAME                   128
#define IDR_MY3DVITYPE                  129
#define IDD_TEST_PANEL                  132
#define IDD_TAB_DIALOG01                135
#define IDD_TAB_DIALOG02                136
#define IDD_TAB_DIALOG00                137
#define IDD_TAB_DIALOG03                138
#define IDD_TAB_DIALOG04                139
#define IDD_TAB_DIALOG07                140
#define IDD_TAB_DIALOG06                141
#define IDD_TAB_DIALOG05                142
#define IDC_CURSOR1                     143
#define IDC_ZOOMIN                      144
#define IDC_ZOOMOUT                     145
#define IDI_ICON1                       146
#define IDD_DIALOG_2D_MESH_INFO         147
#define IDI_ICON2                       148
#define IDD_DIALOG_COMPUTE_INITIAL_VALUE 149
#define IDD_GRAPHICDLG                  150
#define IDC_CURSOR2                     151
#define IDD_DIALOG_SUBDIVIDE_SETTING    152
#define IDD_DIALOG_COLOR                155
#define IDC_TAB_TestPanels              1003
#define IDC_BUTTON_OpenDI               1005
#define IDC_BUTTON_OpenGrid             1006
#define IDC_CHECK_LIGHTING              1007
#define IDC_BUTTON_OpenPLY              1008
#define IDC_BUTTON_RESET                1009
#define IDC_BUTTON_OPEN_2DMESH          1009
#define IDC_BUTTON_MESH_INFOR           1010
#define IDC_STATIC_2D_NODE_NUM_T        1011
#define IDC_STATIC_3D_NODE_NUM_T        1012
#define IDC_STATIC_EDGE_NUM_T           1013
#define IDC_STATIC_2D_NUM               1014
#define IDC_STATIC_3D_NODE_NUM          1014
#define IDC_STATIC_3D_NUM               1015
#define IDC_STATIC_EDGE_NUM             1016
#define IDC_STATIC_3D_EDGE_NUM          1016
#define IDC_STATIC_SAMPLE_GAP_T         1017
#define IDC_BUTTON_ITERATION_1Pass      1017
#define IDC_STATIC_SAMPLE_GAP           1018
#define IDC_BUTTON_ITERATION_THROUGH    1018
#define IDC_STATIC_FACE_NUM_T           1019
#define IDC_BUTTON_JACOBIAN_MAP         1019
#define IDC_STATIC_FACE_NUMBER          1020
#define IDC_STATIC_3D_FACE_NUMBER       1020
#define IDC_CHECK_SHOW_2D_SAMPLING      1020
#define IDC_STATIC_EDGE_NODE_NUM_T      1021
#define IDC_EDIT_Sample_Density         1021
#define IDC_STATIC_BORDER_NODE_NUM      1022
#define IDC_CHECK_SHOW_3D_SAMPLING      1022
#define IDC_STATIC_2D_NODE_NUM_T2       1023
#define IDC_EDIT_Param_Space_Width      1023
#define IDC_STATIC_EDGE_NUM_T2          1024
#define IDC_EDIT_Param_Space_Height     1024
#define IDC_STATIC_2D_NUM2              1025
#define IDC_STATIC_2D_NODE_NUM          1025
#define IDC_CHECK_SPHERICAL             1025
#define IDC_STATIC_EDGE_NUM2            1026
#define IDC_STATIC_2D_EDGE_NUM          1026
#define IDC_CHECK_LABEL                 1026
#define IDC_STATIC_FACE_NUM_T2          1027
#define IDC_CHECK_ARC                   1027
#define IDC_STATIC_FACE_NUMBER2         1028
#define IDC_STATIC_2D_FACE_NUMBER       1028
#define IDC_CHECK_LINE                  1028
#define IDC_STATIC_GENUS_T              1029
#define IDC_CHECK_ErrorDSPhere          1029
#define IDC_STATIC_GENUS_NUM            1030
#define IDC_CHECK_EvenSphere            1030
#define IDC_STATIC_SPECULAR             1033
#define IDC_EDIT_PASSES                 1033
#define IDC_STATIC2                     1034
#define IDC_STATIC_DIFFUSE              1035
#define IDC_RADIO_VERTEX                1036
#define IDC_RADIO_WIREFRAME             1037
#define IDC_RADIO_FACE                  1038
#define IDC_STATIC_AMBIENT              1039
#define IDC_STATIC_GROUND               1040
#define IDC_CHECK_DISABLE_LIGHT         1043
#define IDC_EDIT_ITERATION_LIMIT        1044
#define IDC_EDIT_ERROR_BOUND            1045
#define IDC_EDIT_INCREMENT_BOUND        1046
#define IDC_EDIT_WEIGHT                 1047
#define IDC_BUTTON_INIT                 1048
#define IDC_CHECK_YES                   1050
#define IDC_CHECK_NO                    1051
#define IDC_CHECK_OPTI_NO_OPTI          1052
#define IDC_CHECK_OPTI_GLOBAL           1053
#define IDC_CHECK_OPTI_LOCAL            1054
#define IDC_CHECK_OPTI_MATLAB           1055
#define IDC_CHECK_TARGET_FOUNDAMENTAL   1056
#define IDC_CHECK_TARGET_OURS           1057
#define IDC_CHECK_LW_MODE_EQUI_ANGLE    1058
#define IDC_CHECK_LW_MODE_LENGTH_PRESERVE 1059
#define IDC_STATIC_INPUT_PLY            1060
#define IDC_EDIT_FILE_PATH              1061
#define IDC_BUTTON_INPUT_FILE           1062
#define IDC_LIST_MESSAGE                1063
#define IDC_CHECK_NODE2LABEL            1064
#define EDIT_HISTORY                    1065
#define IDC_CHECK_OPTI_GLOBAL_LOCAL     1066
#define IDC_BUTTON_OPEN_LOG             1067
#define IDC_EDIT_TIMER                  1068
#define IDC_BUTTON1                     1069
#define IDC_BUTTON_DETECT_EDGE          1069
#define IDC_BUTTON_SAVE_2DMESH          1069
#define IDC_MAP1                        1070
#define IDC_BUTTON2                     1070
#define IDC_BUTTON_FIND_INITIAL_TAGENT  1070
#define IDC_BUTTON_1ST                  1070
#define IDC_BUTTON3                     1071
#define IDC_BUTTON_TAGENT_OPTI          1071
#define IDC_BUTTON_POINTCLOULD          1071
#define IDC_BUTTON4                     1072
#define IDC_BUTTON_EDGE_PARAME          1072
#define IDC_BUTTON5                     1073
#define IDC_BUTTON_FLOATER_TUTTE        1073
#define IDC_BUTTON6                     1074
#define IDC_BUTTON_FLOATER_SAMEANGLE    1074
#define IDC_BUTTON7                     1075
#define IDC_BUTTON_FLOATER_KEEP_SHAPE   1075
#define IDC_BUTTON8                     1076
#define IDC_BUTTON_FLOATER_MEANVALUE    1076
#define IDC_BUTTON9                     1077
#define IDC_BUTTON_GENERATE_GEOIMAGE    1077
#define IDC_BUTTON10                    1078
#define IDC_BUTTON_RECONSTRUCTION       1078
#define IDC_BUTTON11                    1079
#define IDC_BUTTON1_1TO4_BAT            1079
#define IDC_BUTTON13                    1081
#define IDC_BUTTON1_SAVE_2DMESH         1081
#define IDC_CHECK_QUICK                 1084
#define IDC_STATIC_LONGEST_EDGE         1085
#define IDC_STATIC_SHORTEST_EDGE        1086
#define IDC_EDIT_INPUT_LEN              1087
#define IDC_CHECK_ACCELERATING          1090
#define IDC_ACCMUL                      1092
#define IDC_CHECK_MEMORYBOOSTER         1093
#define IDC_GRAPHIC1                    1101
#define IDC_GRAPHIC2                    1102
#define IDC_XPOINT                      1104
#define IDC_YPOINT                      1105
#define IDC_MAP2                        1106
#define IDC_OVERLAYED                   1107
#define IDC_VALUE_MMD                   1108
#define IDC_AVERAGE                     1140
#define IDC_MMD                         1141
#define IDC_SX                          2000
#define IDC_SY                          2001
#define IDC_SZ                          2002
#define IDC_RNO                         2003
#define IDC_RXY                         2004
#define IDC_RXZ                         2005
#define IDC_RYZ                         2006
#define IDC_RXYZ                        2007
#define IDC_SLX                         2008
#define IDC_RASURFACE                   2009
#define IDC_SLY                         2009
#define IDC_SLZ                         2010
#define IDC_CRTYPE                      2011
#define IDC_BUBACKCOLOR                 2012
#define IDC_BUMINCOLOR                  2013
#define IDC_SSPEED                      2014
#define IDC_BUMAXCOLOR                  2014
#define IDC_RMOVE                       2015
#define IDC_EDAUTODIV                   2015
#define IDC_RRANDOM                     2016
#define IDC_SPAUTODIV                   2016
#define IDC_RCENTER                     2017
#define IDC_EDCUSTDIV                   2017
#define IDC_RAGRID                      2101
#define IDC_RA2D                        2102
#define ID_VIEW_PAN                     32771
#define ID_VIEW_ZOOM_IN                 32772
#define ID_VIEW_ZOOM_OUT                32773
#define IDM_EDIT_INVERSE                32774
#define ID_EDIT_EQUALIZE                32775
#define ID_EDIT_FourierTransform        32776
#define IDM_EDIT_FFT_PERIDOGRAM         32777
#define IDC_EDIT_GRAPHIC                32778
#define IDC_EDIT_FILTER                 32779
#define ID_EDIT_WaveletTransform        32780
#define ID_EDIT_InverseWaveletTransform 32781
#define IDM_EDIT_DAUB4                  32782
#define IDM_EDIT_DAUB12                 32783
#define IDM_EDIT_DAUB20                 32784
#define IDM_FILE_INFO                   32785
#define ID_VIEW_3D_BROWSER              32786
#define ID_MENUITEM32787                32787
#define ID_CHANGE_MESH_COLOR            32789
#define ID_DEBUG_RL_SETMESH             32790
#define ID_MENUITEM32791                32791
#define ID_MENUI_CAPTURE_IMAGE          32791
#define ID_MENUITEM32792                32792
#define IDM_SetMeshSphere               32793
#define IDM_SAVE_OBJ_AS_PLY             32795
#define IDM_MESH_SUBDIVISION            32796
#define IDM_CONSTRUCT_MODEL_CUBE        32798
#define IDM_MODEL_HEXAHEDRON            32799
#define IDM_MODEL_RESOLVE               32800
#define IDM_MODEL_EXTRUDE               32801
#define IDM_MESH_AVERAGE                32802
#define IDM_FLOOD_FILL                  32803

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        153
#define _APS_NEXT_COMMAND_VALUE         32804
#define _APS_NEXT_CONTROL_VALUE         1094
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
